trigger:
  branches:
    include: ['master', 'v*']
  paths:
    exclude: ['azure-pipelines.yaml', 'README.md', 'LICENSE', 'assets', 'chocolatey', 'GuitarHub.Tests/*']

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  solution: '**/*.sln'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'

pool:
  name: Hosted Windows 2019 with VS2019
  demands:
  - msbuild

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install -g nbgv
  displayName: Install NBGV tool

- script: nbgv cloud -c
  displayName: Set Version

- task: VSBuild@1
  displayName: 'Build solution $(solution)'
  inputs:
    solution: '$(solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: ArchiveFiles@2
  displayName: 'Zip and stage build artifacts'
  inputs:
    rootFolderOrFile: '$(system.defaultworkingdirectory)\GuitarHub\bin\$(BuildConfiguration)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)\GuitarHub-$(Build.BuildNumber).zip'

- script: choco pack --version=$(Build.BuildNumber) --out=$(Build.ArtifactStagingDirectory)
  displayName: Create Chocolatey Package

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
